// Generated by CoffeeScript 1.6.3
(function() {
  var checkSlot, nums, runSlot, startSlot, stopCount, stopSlot, timers;

  timers = [];

  nums = [];

  stopCount = 0;

  startSlot = function() {
    var key, _i, _len;
    for (_i = 0, _len = timers.length; _i < _len; _i++) {
      key = timers[_i];
      console.log(key);
      if (key == null) {
        return;
      }
    }
    runSlot(0);
    runSlot(1);
    return runSlot(2);
  };

  stopSlot = function(n) {
    clearTimeout(timers[n]);
    if (!nums[n]) {
      nums[n] = document.getElementById('num' + n).innerHTML;
      stopCount++;
    }
    if (stopCount === 3) {
      return checkSlot();
    }
  };

  checkSlot = function() {
    if (!nums) {
      return;
    }
    if (nums.length !== 3) {
      return;
    }
    nums.sort;
    if (nums[0] === nums[1] && nums[0] === nums[2]) {
      return alert("全部揃った！");
    } else if (nums[0] === nums[1] || nums[1] === nums[2]) {
      return alert("2つ揃った！");
    } else {
      return alert("残念");
    }
  };

  runSlot = function(n) {
    document.getElementById('num' + n).innerHTML = Math.floor(Math.random() * 10);
    return timers[n] = setTimeout(function() {
      return runSlot(n);
    }, 50);
  };

  startSlot();

  document.getElementById("stop-btn0").onclick = function() {
    return stopSlot(0);
  };

  document.getElementById("stop-btn1").onclick = function() {
    return stopSlot(1);
  };

  document.getElementById("stop-btn2").onclick = function() {
    return stopSlot(2);
  };

  document.getElementById("start-btn").onclick = function() {
    return startSlot();
  };

}).call(this);
