// Generated by CoffeeScript 1.6.3
(function() {
  var checkSlot, nums, runSlot, startSlot, stopSlot, timers;

  timers = [];

  nums = [];

  startSlot = function() {
    document.getElementById("start-btn").removeEventListener("click", startSlot);
    runSlot(0);
    runSlot(1);
    runSlot(2);
    document.getElementById("stop-btn1").addEventListener("click", (function(e) {
      var self;
      self = this;
      stopSlot(self);
      return this.removeEventListener("click", arguments.callee);
    }));
    document.getElementById("stop-btn2").addEventListener("click", (function() {
      var self;
      self = this;
      stopSlot(self);
      return this.removeEventListener("click", arguments.callee);
    }));
    return document.getElementById("stop-btn3").addEventListener("click", (function() {
      var self;
      self = this;
      stopSlot(self);
      return this.removeEventListener("click", arguments.callee);
    }));
  };

  stopSlot = function(self) {
    var n, str;
    str = self.getAttribute("id");
    n = str.replace("stop-btn", "");
    clearTimeout(timers[n - 1]);
    nums.push(+document.getElementById('num' + n).innerHTML);
    if (nums.length === 3) {
      return checkSlot();
    }
  };

  checkSlot = function() {
    var _ref;
    nums.sort();
    if ((nums[0] === (_ref = nums[1]) && _ref === nums[2])) {
      alert("全部揃った！");
    } else if (nums[0] === nums[1] || nums[1] === nums[2]) {
      alert("2つ揃った！");
    } else {
      alert("残念");
    }
    nums = [];
    return document.getElementById("start-btn").addEventListener("click", startSlot);
  };

  runSlot = function(n) {
    document.getElementById('num' + (n + 1)).innerHTML = Math.floor(Math.random() * 10);
    if (timers[n]) {
      clearTimeout(timers[n]);
    }
    return timers[n] = setInterval(function() {
      return runSlot(n);
    }, 50);
  };

  startSlot();

}).call(this);
