// Generated by CoffeeScript 1.6.3
(function() {
  var checkSlot, nums, runSlot, startSlot, stopSlot, timers;

  timers = [];

  nums = [];

  startSlot = function() {
    document.getElementById("start-btn").removeEventListener("click", startSlot);
    runSlot(0);
    runSlot(1);
    runSlot(2);
    document.getElementById("stop-btn0").addEventListener("click", (function() {
      stopSlot(0);
      return this.removeEventListener("click", arguments.callee);
    }));
    document.getElementById("stop-btn1").addEventListener("click", (function() {
      stopSlot(1);
      return this.removeEventListener("click", arguments.callee);
    }));
    return document.getElementById("stop-btn2").addEventListener("click", (function() {
      stopSlot(2);
      return this.removeEventListener("click", arguments.callee);
    }));
  };

  stopSlot = function(n) {
    clearTimeout(timers[n]);
    nums.push(+document.getElementById('num' + n).innerHTML);
    if (nums.length === 3) {
      return checkSlot();
    }
  };

  checkSlot = function() {
    nums.sort();
    if (nums[0] === nums[1] && nums[0] === nums[2] && nums[1] === nums[2]) {
      alert("全部揃った！");
    } else if (nums[0] === nums[1] || nums[1] === nums[2]) {
      alert("2つ揃った！");
    } else {
      alert("残念");
    }
    nums = [];
    console.time("test");
    return document.getElementById("start-btn").addEventListener("click", startSlot);
  };

  runSlot = function(n) {
    document.getElementById('num' + n).innerHTML = Math.floor(Math.random() * 10);
    if (timers[n]) {
      clearTimeout(timers[n]);
    }
    console.time("test");
    return timers[n] = setInterval(function() {
      return runSlot(n);
    }, 50);
  };

  startSlot();

}).call(this);
